name: camtrappy
channels:
    - conda-forge
dependencies:
    - python=3.8
    - opencv=4.5.1
    - numpy=1.20.1
    - pillow=8.1.1
    - scikit-image=0.18.1
    - scikit-learn=0.24.1
    - sqlalchemy=1.4