name: camtrappy-dev
channels:
    - conda-forge
dependencies:
    # required
    - python=3.8
    - opencv=4.5.1
    - numpy=1.20.1
    - pillow=8.1.1
    - pydantic=1.8.2
    - scikit-image=0.18.1
    - scikit-learn=0.24.1
    - sqlalchemy=1.4
    - sqlalchemy-utils=0.37
    - ffmpeg-python

    # interactive development
    - jupyterlab=3.0.0
    - jupyterlab_widgets=1.0.0

    # better version control for notebooks
    - nbdime=3.1.0

    # styling
    - black